import type { TsdownStaleGuardData } from '../src/types'
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { parseHashFile, serializeHashFile, TsdownStaleGuard } from '../src'
import { detectPackageLock, findUp } from '../src/detect'
import { computeCompositeHash, hashFile } from '../src/hash'

describe('test TsdownStaleGuard', () => {
  it('exports plugin factory', () => {
    const plugin = TsdownStaleGuard()
    expect(plugin.name).toBe('tsdown-stale-guard')
  })

  it('accepts custom options', () => {
    const plugin = TsdownStaleGuard({
      hashFile: 'custom.hash.yaml',
      hashOutputs: false,
    })
    expect(plugin.name).toBe('tsdown-stale-guard')
  })
})

describe('hashFile', () => {
  it('hashes a file', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    const filePath = join(dir, 'test.txt')
    await writeFile(filePath, 'hello world')
    const hash = await hashFile(filePath)
    expect(hash).toMatch(/^sha256:[a-f0-9]{64}$/)
    await rm(dir, { recursive: true })
  })

  it('returns consistent hashes', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    const filePath = join(dir, 'test.txt')
    await writeFile(filePath, 'hello world')
    const hash1 = await hashFile(filePath)
    const hash2 = await hashFile(filePath)
    expect(hash1).toBe(hash2)
    await rm(dir, { recursive: true })
  })

  it('produces different hashes for different content', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    const file1 = join(dir, 'a.txt')
    const file2 = join(dir, 'b.txt')
    await writeFile(file1, 'hello')
    await writeFile(file2, 'world')
    const hash1 = await hashFile(file1)
    const hash2 = await hashFile(file2)
    expect(hash1).not.toBe(hash2)
    await rm(dir, { recursive: true })
  })
})

describe('computeCompositeHash', () => {
  it('computes a composite hash', () => {
    const entries = [
      { file: 'a.ts', hash: 'sha256:aaa' },
      { file: 'b.ts', hash: 'sha256:bbb' },
    ]
    const hash = computeCompositeHash(entries)
    expect(hash).toMatch(/^sha256:[a-f0-9]{64}$/)
  })

  it('is order-independent', () => {
    const entries1 = [
      { file: 'a.ts', hash: 'sha256:aaa' },
      { file: 'b.ts', hash: 'sha256:bbb' },
    ]
    const entries2 = [
      { file: 'b.ts', hash: 'sha256:bbb' },
      { file: 'a.ts', hash: 'sha256:aaa' },
    ]
    expect(computeCompositeHash(entries1)).toBe(computeCompositeHash(entries2))
  })

  it('changes when an entry changes', () => {
    const entries1 = [
      { file: 'a.ts', hash: 'sha256:aaa' },
    ]
    const entries2 = [
      { file: 'a.ts', hash: 'sha256:bbb' },
    ]
    expect(computeCompositeHash(entries1)).not.toBe(computeCompositeHash(entries2))
  })
})

describe('hash file serialization', () => {
  const data: TsdownStaleGuardData = {
    version: 1,
    hash: 'sha256:composite123',
    configs: [{ file: 'tsdown.config.ts', hash: 'sha256:config123' }],
    lockfile: { file: '../../pnpm-lock.yaml', hash: 'sha256:lock123' },
    sources: [
      { file: 'src/index.ts', hash: 'sha256:src123' },
    ],
    outputs: [
      { file: 'dist/index.mjs', hash: 'sha256:out123' },
    ],
  }

  it('round-trips correctly', () => {
    const serialized = serializeHashFile(data)
    const parsed = parseHashFile(serialized)
    expect(parsed).toEqual(data)
  })

  it('includes header comment', () => {
    const serialized = serializeHashFile(data)
    expect(serialized).toContain('# auto-generated by tsdown-stale-guard')
    expect(serialized).toContain('# DO NOT EDIT')
  })

  it('handles missing optional fields', () => {
    const minimal: TsdownStaleGuardData = {
      version: 1,
      hash: 'sha256:minimal',
      sources: [{ file: 'src/index.ts', hash: 'sha256:aaa' }],
      outputs: [],
    }
    const serialized = serializeHashFile(minimal)
    const parsed = parseHashFile(serialized)
    expect(parsed.configs).toEqual([])
    expect(parsed.lockfile).toBeUndefined()
    expect(parsed.sources).toEqual(minimal.sources)
    expect(parsed.outputs).toEqual([])
  })

  it('preserves multiple sources sorted', () => {
    const multi: TsdownStaleGuardData = {
      version: 1,
      hash: 'sha256:multi',
      configs: [],
      sources: [
        { file: 'src/a.ts', hash: 'sha256:aaa' },
        { file: 'src/b.ts', hash: 'sha256:bbb' },
        { file: 'src/c.ts', hash: 'sha256:ccc' },
      ],
      outputs: [
        { file: 'dist/index.mjs', hash: 'sha256:out1' },
        { file: 'dist/index.d.mts', hash: 'sha256:out2' },
      ],
    }
    const parsed = parseHashFile(serializeHashFile(multi))
    expect(parsed.sources).toHaveLength(3)
    expect(parsed.outputs).toHaveLength(2)
    expect(parsed).toEqual(multi)
  })
})

describe('findUp', () => {
  it('finds a file in current directory', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    const filePath = join(dir, 'target.txt')
    await writeFile(filePath, '')
    const result = findUp(['target.txt'], dir)
    expect(result).toBe(filePath)
    await rm(dir, { recursive: true })
  })

  it('finds a file in parent directory', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    const child = join(dir, 'child')
    const filePath = join(dir, 'target.txt')
    await writeFile(filePath, '')
    await mkdir(child)
    const result = findUp(['target.txt'], child)
    expect(result).toBe(filePath)
    await rm(dir, { recursive: true })
  })

  it('finds first matching name', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    await writeFile(join(dir, 'second.txt'), '')
    await writeFile(join(dir, 'first.txt'), '')
    const result = findUp(['first.txt', 'second.txt'], dir)
    expect(result).toBe(join(dir, 'first.txt'))
    await rm(dir, { recursive: true })
  })

  it('finds closest match when present in multiple levels', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tsdown-stale-guard-'))
    const child = join(dir, 'child')
    await mkdir(child)
    await writeFile(join(dir, 'target.txt'), 'parent')
    await writeFile(join(child, 'target.txt'), 'child')
    const result = findUp(['target.txt'], child)
    expect(result).toBe(join(child, 'target.txt'))
    await rm(dir, { recursive: true })
  })

  it('returns undefined when not found', () => {
    const result = findUp(['nonexistent-file-12345.txt'], tmpdir())
    expect(result).toBeUndefined()
  })
})

describe('detect', () => {
  it('detectPackageLock finds pnpm-lock.yaml', () => {
    const result = detectPackageLock(process.cwd())
    expect(result).toBeDefined()
    expect(result).toContain('pnpm-lock.yaml')
  })
})
