/**
 * Generated by tsnapi — public API snapshot of `tsdown-stale-guard` */
// Interfaces
export interface CheckChange {
  type: 'changed' | 'added' | 'removed';
  category: 'config' | 'lockfile' | 'source' | 'output';
  file: string;
}
export interface CheckOptions {
  hashFile?: string;
  root?: string;
}
export interface CheckResult {
  fresh: boolean;
  stale: boolean;
  changes: CheckChange[];
}
export interface StaleGuardData {
  version: 1;
  hash: string;
  configs?: StaleGuardEntry[];
  lockfile?: StaleGuardEntry;
  sources: StaleGuardEntry[];
  outputs: StaleGuardEntry[];
}
export interface StaleGuardEntry {
  file: string;
  hash: string;
}
export interface StaleGuardRecorderOptions {
  hashFile?: string;
  root?: string;
  hashOutputs?: boolean;
}

// Functions
export declare function checkBuildState(_?: CheckOptions): Promise<CheckResult>;
export declare function parseHashFile(_: string): StaleGuardData;
export declare function readHashFile(_: string): Promise<StaleGuardData>;
export declare function serializeHashFile(_: StaleGuardData): string;
export declare function StaleGuardRecorder(_?: StaleGuardRecorderOptions): TsdownPlugin;