/**
 * Generated by tsnapi — public API snapshot of `tsdown-lock` */
// Interfaces
export interface CheckChange {
  type: 'changed' | 'added' | 'removed';
  category: 'config' | 'lockfile' | 'source' | 'output';
  file: string;
}
export interface CheckOptions {
  lockFile?: string;
  root?: string;
}
export interface CheckResult {
  fresh: boolean;
  changes: CheckChange[];
}
export interface TsdownLockData {
  version: 1;
  hash: string;
  config?: TsdownLockEntry;
  lockfile?: TsdownLockEntry;
  sources: TsdownLockEntry[];
  outputs: TsdownLockEntry[];
}
export interface TsdownLockEntry {
  file: string;
  hash: string;
}
export interface TsdownLockPluginOptions {
  lockFile?: string;
  root?: string;
  hashOutputs?: boolean;
}

// Functions
export declare function checkBuildFreshness(_?: CheckOptions): Promise<CheckResult>;
export declare function parseLockFile(_: string): TsdownLockData;
export declare function readLockFile(_: string): Promise<TsdownLockData>;
export declare function serializeLockFile(_: TsdownLockData): string;
export declare function TsdownLock(_?: TsdownLockPluginOptions): Plugin;
