/**
 * Generated by tsnapi — public API snapshot of `tsdown-stale-guard`
 */
// #region Interfaces
export interface CheckChange {
  type: 'changed' | 'added' | 'removed';
  category: 'config' | 'lockfile' | 'source' | 'output';
  file: string;
}
export interface CheckOptions {
  hashFile?: string;
  root?: string;
}
export interface CheckResult {
  fresh: boolean;
  stale: boolean;
  changes: CheckChange[];
}
export interface StaleGuardData {
  version: 1;
  hash: string;
  configs?: StaleGuardEntry[];
  lockfile?: StaleGuardEntry;
  sources: StaleGuardEntry[];
  outputs: StaleGuardEntry[];
}
export interface StaleGuardEntry {
  file: string;
  hash: string;
}
export interface StaleGuardRecorderOptions {
  hashFile?: string;
  root?: string;
  hashOutputs?: boolean;
}
// #endregion

// #region Functions
export declare function checkBuildState(_?: CheckOptions): Promise<CheckResult>;
export declare function guardStaleBuild(_?: CheckOptions): Promise<void>;
export declare function parseHashFile(_: string): StaleGuardData;
export declare function readHashFile(_: string): Promise<StaleGuardData>;
export declare function serializeHashFile(_: StaleGuardData): string;
export declare function StaleGuardRecorder(_?: StaleGuardRecorderOptions): TsdownPlugin;
// #endregion

// #region Variables
export declare const diagnostics: import("logs-sdk").DiagnosticsResult<{
  TSDSG0001: {
    message: string;
    why: string;
    fix: string;
  };
  TSDSG0002: {
    message: (p: {
      root: string;
      changeCount: number;
    }) => string;
    why: string;
    fix: string;
  };
  TSDSG0003: {
    message: (p: {
      root: string;
    }) => string;
    why: string;
    fix: string;
  };
}>;
export declare const log: import("logs-sdk").Logger<[import("logs-sdk").DiagnosticsResult<{
  TSDSG0001: {
    message: string;
    why: string;
    fix: string;
  };
  TSDSG0002: {
    message: (p: {
      root: string;
      changeCount: number;
    }) => string;
    why: string;
    fix: string;
  };
  TSDSG0003: {
    message: (p: {
      root: string;
    }) => string;
    why: string;
    fix: string;
  };
}>]>;
// #endregion