import type { TsdownStaleGuardData, TsdownStaleGuardEntry } from './types'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { stringify, parse as yamlParse } from 'yaml'

const HEADER = '# auto-generated by tsdown-stale-guard\n# DO NOT EDIT\n'

export function serializeHashFile(data: TsdownStaleGuardData): string {
  const obj: Record<string, unknown> = {
    version: data.version,
    hash: data.hash,
  }

  if (data.config)
    obj.config = { [data.config.file]: data.config.hash }

  if (data.lockfile)
    obj.lockfile = { [data.lockfile.file]: data.lockfile.hash }

  if (data.sources.length > 0) {
    obj.sources = Object.fromEntries(
      data.sources.map(e => [e.file, e.hash]),
    )
  }

  if (data.outputs.length > 0) {
    obj.outputs = Object.fromEntries(
      data.outputs.map(e => [e.file, e.hash]),
    )
  }

  return HEADER + stringify(obj, { lineWidth: 0 })
}

export function parseHashFile(content: string): TsdownStaleGuardData {
  const obj = yamlParse(content) as Record<string, unknown>

  return {
    version: obj.version as 1,
    hash: obj.hash as string,
    config: parseSection(obj.config as Record<string, string> | undefined),
    lockfile: parseSection(obj.lockfile as Record<string, string> | undefined),
    sources: parseSectionList(obj.sources as Record<string, string> | undefined),
    outputs: parseSectionList(obj.outputs as Record<string, string> | undefined),
  }
}

function parseSection(section: Record<string, string> | undefined): TsdownStaleGuardEntry | undefined {
  if (!section)
    return undefined
  const entries = Object.entries(section)
  if (entries.length === 0)
    return undefined
  const [file, hash] = entries[0]
  return { file, hash }
}

function parseSectionList(section: Record<string, string> | undefined): TsdownStaleGuardEntry[] {
  if (!section)
    return []
  return Object.entries(section).map(([file, hash]) => ({ file, hash }))
}

export async function readHashFile(path: string): Promise<TsdownStaleGuardData> {
  const content = await readFile(path, 'utf-8')
  return parseHashFile(content)
}

export async function writeHashFile(path: string, data: TsdownStaleGuardData): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, serializeHashFile(data), 'utf-8')
}
