name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@main
    with:
      os-matrix: '"ubuntu-latest", "windows-latest", "macos-latest"'
      node-versions: '"lts/*"'
